### PR TITLE
update chinese translation

### PR DESCRIPTION
**Pull request by TUsama**

### CODE REVIEW

**Comment by TUsama** [comment]
btw，I wonder if i could reprint it to MCBBS which is the most popular chinese minecraft forum, i think chinese player will really like your mod: ) and i will only give the dwonload address to link to curseforge page.

**Comment by SwissCheese5** [comment]
Excellent work, thank you!

**Comment by SwissCheese5** [comment]
You can post the mod there but the download link must lead to our curseforge page only. no exceptions

**Comment by TUsama** [comment]
ok，I'll never do that

**Pull request merged**
